### ISSUE TITLE
How to derive sea surface elevation？

### ISSUE THREAD

**Issue by Springder** [ThijsKuipers1995/FFTOcean#1]
What should I do if I want to export the sea surface elevation separately？ `ocean` class doesn't seem to return a value or matrix.

**Comment by ThijsKuipers1995** [comment]
The ocean surface's x, y, and z displacements are stored in `ocean.surface_buffer`. The `ocean.calculate_ocean_surface(time: float)` method updates and returns `ocean.surface_buffer` for a given time.

**Comment by Springder** [comment]
Thank you!
Currently, I am learning sea spectra modeling. Found out that there are actually quite a few sea spectra models out there. Why do we use Phillip's Spectrum model instead of PM model or JONSWAP model？

**Comment by ThijsKuipers1995** [comment]
You can certainly use other spectra besides Philip's. JONSWAP is a good choice because it offers more control over how the ocean behaves than Phillip's spectrum. The downside would be the larger number of parameters that need to be tuned to achieve good-looking waves. I made this project because I wanted to learn how to simulate large water surfaces (I have always been interested in water simulations for some reason). I used Phillip's spectrum specifically because this project is an implementation of Tessendorf's paper, and he uses Phillip's.

**Comment by Springder** [comment]
Thank you for your reply! I previously mistakenly thought that the Phillips model was the best choice, because it was widely used in 3D games. But many documents introduce other models but not Phillip. From your description, I realise the reason why it is widely used.

**Comment by Springder** [comment]
I read through the source code and a question arose. `resolution` is actually the size of the x or y, not the spatial resolution. The actual spatial resolution should be `4/resolution.` Is this the right way to understand it?

**Comment by ThijsKuipers1995** [comment]
Yes, thats correct. The surface simulation only returns the dx,dy, and dz displacements for each (x, y) position. The magnitude of the displacement can be scaled to any arbitrary size. I dont really remember why I made the grid to be 4x4 centered at zero. I believe it was because it just looked right when visualizing the surface (matplotlib really is not meant for rendering 3d animations :P).  The resolution parameter refers to the number of points in the grid, not its ‘physical’ size.
